version: '3.8'

services:
  backend:
    build: ./backend
    container_name: happybendis-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    networks:
      - happybendis-network

  frontend:
    build: ./frontend
    container_name: happybendis-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - happybendis-network

networks:
  happybendis-network:
    driver: bridge
